apiVersion: v1
kind: Service
metadata:
  name: immich-service
  namespace: immich
spec:
  selector:
    app.kubernetes.io/instance: immich
  ports:
    - name: http
      protocol: TCP
      port: 2283
      targetPort: 2283
  type: LoadBalancer
  loadBalancerIP: 192.168.50.167
